Ic solutions info theory 1
slds-lmu/lecture_sl pull request #11
Opened 2022-11-10 10:30 UTC by patriciomassaro

2022-11-10 10:32 UTC, patriciomassaro commented
![](https://github.trello.services/images/mini-trello-icon.png) [IC Solutions SL - Sheet 5](https://trello.com/c/nK3cJ1m3/232-ic-solutions-sl-sheet-5)

2022-11-17 16:37 UTC, ludwigbothmann commented on exercises/information-theory/ex_rnw/ic_sol_entropy_binary_classification.Rnw
> +      As $\epsilon$ and $x$ are have a deterministic relation, the uncertainty introduced by the $\psi$ function is 0. The entropy of $\epsilon$ is given only by the entropy of $x$
delete "are"

2022-11-18 09:59 UTC, ludwigbothmann requested changes
Please also add the pdfs in exercise-pdf in the end

2022-11-18 11:26 UTC, patriciomassaro commented on exercises/information-theory/ex_rnw/ic_sol_entropy_binary_classification.Rnw
> +      H(y|x) &= \E_x [H(y|x=x)] = \sum_{x \in \Omega_x } H(y|x=x) \\
Yes, you are right. But I wrote $P(x=x)$ instead, as theta is already defined as the probability that x = 1

2022-11-18 11:35 UTC, patriciomassaro commented
- PDFs added
- Solved the typos
- Instead of adding a theta, I added something different after the sum, please take a look at that and let me know your opinion.

2022-11-21 17:44 UTC, patriciomassaro commented
- I moved the Entropy exercise to the second IC exercise sheet of Info Theory
- I added the KL divergence exercise to the first IC exercise sheet and uploaded a draft for the solution.

2022-11-25 10:00 UTC, ludwigbothmann approved these changes

2022-11-25 10:00 UTC, merged