IC exercise sheet 7
slds-lmu/lecture_sl pull request #17
Opened 2022-11-29 11:56 UTC by patriciomassaro

2022-11-30 12:05 UTC, patriciomassaro commented
![](https://github.trello.services/images/mini-trello-icon.png) [IC Solutions SL - Sheet 7](https://trello.com/c/60GjRobY/241-ic-solutions-sl-sheet-7)

2022-12-16 16:26 UTC, ludwigbothmann requested changes
just some small comments @patriciomassaro

2022-12-16 16:26 UTC, ludwigbothmann commented on exercises/cod/ic_cod.Rnw
> +\aufgabe{Quiz Time}{
We do not need this, please comment out

2022-12-23 11:50 UTC, ludwigbothmann approved these changes

2022-12-23 11:50 UTC, merged