Collectiions and cleanup multiclass
slds-lmu/lecture_sl pull request #32
Opened 2023-01-25 11:05 UTC by patriciomassaro

Reminder that after merging I need to: 

- Modify the links for the exercise sheets in the moodle
- Modify the links in the master schedule

2023-01-25 11:13 UTC, patriciomassaro commented
![](https://github.trello.services/images/mini-trello-icon.png) [Collections SL](https://trello.com/c/TH0En9fe/253-collections-sl)

2023-01-27 17:09 UTC, ludwigbothmann requested changes
We only need 1 exercise sheet in that case, exactly the one we used this winter term. The other exercises are collected in the "collections". Having more sheets - which we then did not used, just confuses (at least me). Also please make sure, that in `exercises-pdf` is just the same number of exercise sheets.

2023-02-03 11:19 UTC, patriciomassaro commented
> We only need 1 exercise sheet in that case, exactly the one we used this winter term. The other exercises are collected in the "collections". Having more sheets - which we then did not used, just confuses (at least me). Also please make sure, that in `exercises-pdf` is just the same number of exercise sheets.

Great, from now on I'll follow that guideline ( "Only exercise sheets from this winter will remain, the rest can be found in the collection") 

I will then open a new PR for advriskmin, cause we use the sheets that finish with _1_22.

2023-02-03 15:02 UTC, ludwigbothmann approved these changes

2023-02-03 15:03 UTC, merged